package types

import "cosmossdk.io/errors"

// x/staking module sentinel errors
var (
	ErrEmptyValidatorAddr              = errors.Register(ModuleName, 1002, "empty validator address")
	ErrNoValidatorFound                = errors.Register(ModuleName, 1003, "validator does not exist")
	ErrValidatorOwnerExists            = errors.Register(ModuleName, 1004, "validator already exist for this operator address; must use new validator operator address")
	ErrValidatorPubKeyExists           = errors.Register(ModuleName, 1005, "validator already exist for this pubkey; must use new validator pubkey")
	ErrValidatorPubKeyTypeNotSupported = errors.Register(ModuleName, 1006, "validator pubkey type is not supported")
	ErrValidatorJailed                 = errors.Register(ModuleName, 1007, "validator for this address is currently jailed")
	ErrBadRemoveValidator              = errors.Register(ModuleName, 1008, "failed to remove validator")
	ErrCommissionNegative              = errors.Register(ModuleName, 1009, "commission must be positive")
	ErrCommissionHuge                  = errors.Register(ModuleName, 10010, "commission cannot be more than 100%")
	ErrCommissionGTMaxRate             = errors.Register(ModuleName, 10011, "commission cannot be more than the max rate")
	ErrCommissionUpdateTime            = errors.Register(ModuleName, 10012, "commission cannot be changed more than once in 24h")
	ErrCommissionChangeRateNegative    = errors.Register(ModuleName, 10013, "commission change rate must be positive")
	ErrCommissionChangeRateGTMaxRate   = errors.Register(ModuleName, 10014, "commission change rate cannot be more than the max rate")
	ErrCommissionGTMaxChangeRate       = errors.Register(ModuleName, 10015, "commission cannot be changed more than max change rate")
	ErrSelfDelegationBelowMinimum      = errors.Register(ModuleName, 10016, "validator's self delegation must be greater than their minimum self delegation")
	ErrMinSelfDelegationDecreased      = errors.Register(ModuleName, 10017, "minimum self delegation cannot be decrease")
	ErrEmptyDelegatorAddr              = errors.Register(ModuleName, 10018, "empty delegator address")
	ErrNoDelegation                    = errors.Register(ModuleName, 10019, "no delegation for (address, validator) tuple")
	ErrBadDelegatorAddr                = errors.Register(ModuleName, 10020, "delegator does not exist with address")
	ErrNoDelegatorForAddress           = errors.Register(ModuleName, 10021, "delegator does not contain delegation")
	ErrInsufficientShares              = errors.Register(ModuleName, 10022, "insufficient delegation shares")
	ErrDelegationValidatorEmpty        = errors.Register(ModuleName, 10023, "cannot delegate to an empty validator")
	ErrNotEnoughDelegationShares       = errors.Register(ModuleName, 10024, "not enough delegation shares")
	ErrNotMature                       = errors.Register(ModuleName, 10025, "entry not mature")
	ErrNoUnbondingDelegation           = errors.Register(ModuleName, 10026, "no unbonding delegation found")
	ErrMaxUnbondingDelegationEntries   = errors.Register(ModuleName, 10027, "too many unbonding delegation entries for (delegator, validator) tuple")
	ErrNoRedelegation                  = errors.Register(ModuleName, 10028, "no redelegation found")
	ErrSelfRedelegation                = errors.Register(ModuleName, 10029, "cannot redelegate to the same validator")
	ErrTinyRedelegationAmount          = errors.Register(ModuleName, 10030, "too few tokens to redelegate (truncates to zero tokens)")
	ErrBadRedelegationDst              = errors.Register(ModuleName, 10031, "redelegation destination validator not found")
	ErrTransitiveRedelegation          = errors.Register(ModuleName, 10032, "redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation")
	ErrMaxRedelegationEntries          = errors.Register(ModuleName, 10033, "too many redelegation entries for (delegator, src-validator, dst-validator) tuple")
	ErrDelegatorShareExRateInvalid     = errors.Register(ModuleName, 10034, "cannot delegate to validators with invalid (zero) ex-rate")
	ErrBothShareMsgsGiven              = errors.Register(ModuleName, 10035, "both shares amount and shares percent provided")
	ErrNeitherShareMsgsGiven           = errors.Register(ModuleName, 10036, "neither shares amount nor shares percent provided")
	ErrInvalidHistoricalInfo           = errors.Register(ModuleName, 10037, "invalid historical info")
	ErrNoHistoricalInfo                = errors.Register(ModuleName, 10038, "no historical info found")
	ErrEmptyValidatorPubKey            = errors.Register(ModuleName, 10039, "empty validator public key")
	ErrCommissionLTMinRate             = errors.Register(ModuleName, 10040, "commission cannot be less than min rate")
	ErrUnbondingNotFound               = errors.Register(ModuleName, 10041, "unbonding operation not found")
	ErrUnbondingOnHoldRefCountNegative = errors.Register(ModuleName, 10042, "cannot un-hold unbonding operation that is not on hold")
	ErrInvalidSigner                   = errors.Register(ModuleName, 10043, "expected authority account as only signer for proposal message")
	ErrBadRedelegationSrc              = errors.Register(ModuleName, 10044, "redelegation source validator not found")
	ErrNoUnbondingType                 = errors.Register(ModuleName, 10045, "unbonding type not found")
)
