# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/upgrade/v1beta1/tx.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'cosmos/upgrade/v1beta1/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.upgrade.v1beta1 import upgrade_pb2 as cosmos_dot_upgrade_dot_v1beta1_dot_upgrade__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from amino import amino_pb2 as amino_dot_amino__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63osmos/upgrade/v1beta1/tx.proto\x12\x16\x63osmos.upgrade.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a$cosmos/upgrade/v1beta1/upgrade.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x11\x61mino/amino.proto\"\xce\x01\n\x12MsgSoftwareUpgrade\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12;\n\x04plan\x18\x02 \x01(\x0b\x32\x1c.cosmos.upgrade.v1beta1.PlanB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x04plan:C\xd2\xb4-\x0f\x63osmos-sdk 0.46\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*\x1d\x63osmos-sdk/MsgSoftwareUpgrade\"1\n\x1aMsgSoftwareUpgradeResponse:\x13\xd2\xb4-\x0f\x63osmos-sdk 0.46\"\x8d\x01\n\x10MsgCancelUpgrade\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority:A\xd2\xb4-\x0f\x63osmos-sdk 0.46\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*\x1b\x63osmos-sdk/MsgCancelUpgrade\"/\n\x18MsgCancelUpgradeResponse:\x13\xd2\xb4-\x0f\x63osmos-sdk 0.462\x98\x02\n\x03Msg\x12\x86\x01\n\x0fSoftwareUpgrade\x12*.cosmos.upgrade.v1beta1.MsgSoftwareUpgrade\x1a\x32.cosmos.upgrade.v1beta1.MsgSoftwareUpgradeResponse\"\x13\xca\xb4-\x0f\x63osmos-sdk 0.46\x12\x80\x01\n\rCancelUpgrade\x12(.cosmos.upgrade.v1beta1.MsgCancelUpgrade\x1a\x30.cosmos.upgrade.v1beta1.MsgCancelUpgradeResponse\"\x13\xca\xb4-\x0f\x63osmos-sdk 0.46\x1a\x05\x80\xe7\xb0*\x01\x42\x1eZ\x1c\x63osmossdk.io/x/upgrade/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.upgrade.v1beta1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034cosmossdk.io/x/upgrade/types'
  _globals['_MSGSOFTWAREUPGRADE'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGSOFTWAREUPGRADE'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGSOFTWAREUPGRADE'].fields_by_name['plan']._loaded_options = None
  _globals['_MSGSOFTWAREUPGRADE'].fields_by_name['plan']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGSOFTWAREUPGRADE']._loaded_options = None
  _globals['_MSGSOFTWAREUPGRADE']._serialized_options = b'\322\264-\017cosmos-sdk 0.46\202\347\260*\tauthority\212\347\260*\035cosmos-sdk/MsgSoftwareUpgrade'
  _globals['_MSGSOFTWAREUPGRADERESPONSE']._loaded_options = None
  _globals['_MSGSOFTWAREUPGRADERESPONSE']._serialized_options = b'\322\264-\017cosmos-sdk 0.46'
  _globals['_MSGCANCELUPGRADE'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGCANCELUPGRADE'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGCANCELUPGRADE']._loaded_options = None
  _globals['_MSGCANCELUPGRADE']._serialized_options = b'\322\264-\017cosmos-sdk 0.46\202\347\260*\tauthority\212\347\260*\033cosmos-sdk/MsgCancelUpgrade'
  _globals['_MSGCANCELUPGRADERESPONSE']._loaded_options = None
  _globals['_MSGCANCELUPGRADERESPONSE']._serialized_options = b'\322\264-\017cosmos-sdk 0.46'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSG'].methods_by_name['SoftwareUpgrade']._loaded_options = None
  _globals['_MSG'].methods_by_name['SoftwareUpgrade']._serialized_options = b'\312\264-\017cosmos-sdk 0.46'
  _globals['_MSG'].methods_by_name['CancelUpgrade']._loaded_options = None
  _globals['_MSG'].methods_by_name['CancelUpgrade']._serialized_options = b'\312\264-\017cosmos-sdk 0.46'
  _globals['_MSGSOFTWAREUPGRADE']._serialized_start=191
  _globals['_MSGSOFTWAREUPGRADE']._serialized_end=397
  _globals['_MSGSOFTWAREUPGRADERESPONSE']._serialized_start=399
  _globals['_MSGSOFTWAREUPGRADERESPONSE']._serialized_end=448
  _globals['_MSGCANCELUPGRADE']._serialized_start=451
  _globals['_MSGCANCELUPGRADE']._serialized_end=592
  _globals['_MSGCANCELUPGRADERESPONSE']._serialized_start=594
  _globals['_MSGCANCELUPGRADERESPONSE']._serialized_end=641
  _globals['_MSG']._serialized_start=644
  _globals['_MSG']._serialized_end=924
# @@protoc_insertion_point(module_scope)
