# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from zrchain.bedrock import tx_pb2 as zrchain_dot_bedrock_dot_tx__pb2


class MsgStub(object):
    """Msg defines the Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/zrchain.bedrock.Msg/UpdateParams',
                request_serializer=zrchain_dot_bedrock_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=zrchain_dot_bedrock_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                )
        self.Swap = channel.unary_unary(
                '/zrchain.bedrock.Msg/Swap',
                request_serializer=zrchain_dot_bedrock_dot_tx__pb2.MsgSwap.SerializeToString,
                response_deserializer=zrchain_dot_bedrock_dot_tx__pb2.MsgSwapResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the Msg service.
    """

    def UpdateParams(self, request, context):
        """UpdateParams defines a (governance) operation for updating the module
        parameters. The authority defaults to the x/gov module account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swap(self, request, context):
        """Swap defines a (cross-chain) swap operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=zrchain_dot_bedrock_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=zrchain_dot_bedrock_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
            'Swap': grpc.unary_unary_rpc_method_handler(
                    servicer.Swap,
                    request_deserializer=zrchain_dot_bedrock_dot_tx__pb2.MsgSwap.FromString,
                    response_serializer=zrchain_dot_bedrock_dot_tx__pb2.MsgSwapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zrchain.bedrock.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the Msg service.
    """

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zrchain.bedrock.Msg/UpdateParams',
            zrchain_dot_bedrock_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            zrchain_dot_bedrock_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Swap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zrchain.bedrock.Msg/Swap',
            zrchain_dot_bedrock_dot_tx__pb2.MsgSwap.SerializeToString,
            zrchain_dot_bedrock_dot_tx__pb2.MsgSwapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
