// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zrchain/dct/mint.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MintTransactionStatus int32

const (
	MintTransactionStatus_MINT_TRANSACTION_STATUS_UNSPECIFIED MintTransactionStatus = 0
	MintTransactionStatus_MINT_TRANSACTION_STATUS_DEPOSITED   MintTransactionStatus = 1
	MintTransactionStatus_MINT_TRANSACTION_STATUS_STAKED      MintTransactionStatus = 2
	MintTransactionStatus_MINT_TRANSACTION_STATUS_MINTED      MintTransactionStatus = 3
)

var MintTransactionStatus_name = map[int32]string{
	0: "MINT_TRANSACTION_STATUS_UNSPECIFIED",
	1: "MINT_TRANSACTION_STATUS_DEPOSITED",
	2: "MINT_TRANSACTION_STATUS_STAKED",
	3: "MINT_TRANSACTION_STATUS_MINTED",
}

var MintTransactionStatus_value = map[string]int32{
	"MINT_TRANSACTION_STATUS_UNSPECIFIED": 0,
	"MINT_TRANSACTION_STATUS_DEPOSITED":   1,
	"MINT_TRANSACTION_STATUS_STAKED":      2,
	"MINT_TRANSACTION_STATUS_MINTED":      3,
}

func (x MintTransactionStatus) String() string {
	return proto.EnumName(MintTransactionStatus_name, int32(x))
}

func (MintTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{0}
}

// WalletType specifies the Layer 1 blockchain that this wallet will be used
// for.
type WalletType int32

const (
	// The wallet type is missing (all wallets will be derived)
	WalletType_WALLET_TYPE_UNSPECIFIED WalletType = 0
	// The wallet type for native cosmos accounts
	WalletType_WALLET_TYPE_NATIVE WalletType = 1
	// The wallet type for mainnet ETH and its ERC-20 tokens
	WalletType_WALLET_TYPE_EVM WalletType = 2
	// The Wallet type for Testnet BTC
	WalletType_WALLET_TYPE_BTC_TESTNET WalletType = 3
	// The Wallet type for Mainnet BTC
	WalletType_WALLET_TYPE_BTC_MAINNET WalletType = 4
	// The Wallet type for RegNet - Local Test Network
	WalletType_WALLET_TYPE_BTC_REGNET WalletType = 5
	// Wallet type for Solana
	WalletType_WALLET_TYPE_SOLANA WalletType = 6
)

var WalletType_name = map[int32]string{
	0: "WALLET_TYPE_UNSPECIFIED",
	1: "WALLET_TYPE_NATIVE",
	2: "WALLET_TYPE_EVM",
	3: "WALLET_TYPE_BTC_TESTNET",
	4: "WALLET_TYPE_BTC_MAINNET",
	5: "WALLET_TYPE_BTC_REGNET",
	6: "WALLET_TYPE_SOLANA",
}

var WalletType_value = map[string]int32{
	"WALLET_TYPE_UNSPECIFIED": 0,
	"WALLET_TYPE_NATIVE":      1,
	"WALLET_TYPE_EVM":         2,
	"WALLET_TYPE_BTC_TESTNET": 3,
	"WALLET_TYPE_BTC_MAINNET": 4,
	"WALLET_TYPE_BTC_REGNET":  5,
	"WALLET_TYPE_SOLANA":      6,
}

func (x WalletType) String() string {
	return proto.EnumName(WalletType_name, int32(x))
}

func (WalletType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{1}
}

type NonceData struct {
	Nonce     uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Counter   uint64 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	Skip      bool   `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	PrevNonce uint64 `protobuf:"varint,4,opt,name=prev_nonce,json=prevNonce,proto3" json:"prev_nonce,omitempty"`
}

func (m *NonceData) Reset()         { *m = NonceData{} }
func (m *NonceData) String() string { return proto.CompactTextString(m) }
func (*NonceData) ProtoMessage()    {}
func (*NonceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{0}
}
func (m *NonceData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NonceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NonceData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NonceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceData.Merge(m, src)
}
func (m *NonceData) XXX_Size() int {
	return m.Size()
}
func (m *NonceData) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceData.DiscardUnknown(m)
}

var xxx_messageInfo_NonceData proto.InternalMessageInfo

func (m *NonceData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *NonceData) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *NonceData) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

func (m *NonceData) GetPrevNonce() uint64 {
	if m != nil {
		return m.PrevNonce
	}
	return 0
}

type RequestedBitcoinHeaders struct {
	Heights []int64 `protobuf:"varint,1,rep,packed,name=heights,proto3" json:"heights,omitempty"`
}

func (m *RequestedBitcoinHeaders) Reset()         { *m = RequestedBitcoinHeaders{} }
func (m *RequestedBitcoinHeaders) String() string { return proto.CompactTextString(m) }
func (*RequestedBitcoinHeaders) ProtoMessage()    {}
func (*RequestedBitcoinHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{1}
}
func (m *RequestedBitcoinHeaders) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestedBitcoinHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestedBitcoinHeaders.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestedBitcoinHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestedBitcoinHeaders.Merge(m, src)
}
func (m *RequestedBitcoinHeaders) XXX_Size() int {
	return m.Size()
}
func (m *RequestedBitcoinHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestedBitcoinHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_RequestedBitcoinHeaders proto.InternalMessageInfo

func (m *RequestedBitcoinHeaders) GetHeights() []int64 {
	if m != nil {
		return m.Heights
	}
	return nil
}

type LockTransaction struct {
	RawTx         string `protobuf:"bytes,1,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	Vout          uint64 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Sender        string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	MintRecipient string `protobuf:"bytes,4,opt,name=mint_recipient,json=mintRecipient,proto3" json:"mint_recipient,omitempty"`
	Amount        uint64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	BlockHeight   int64  `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Asset         Asset  `protobuf:"varint,7,opt,name=asset,proto3,enum=zrchain.dct.Asset" json:"asset,omitempty"`
}

func (m *LockTransaction) Reset()         { *m = LockTransaction{} }
func (m *LockTransaction) String() string { return proto.CompactTextString(m) }
func (*LockTransaction) ProtoMessage()    {}
func (*LockTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{2}
}
func (m *LockTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockTransaction.Merge(m, src)
}
func (m *LockTransaction) XXX_Size() int {
	return m.Size()
}
func (m *LockTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_LockTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_LockTransaction proto.InternalMessageInfo

func (m *LockTransaction) GetRawTx() string {
	if m != nil {
		return m.RawTx
	}
	return ""
}

func (m *LockTransaction) GetVout() uint64 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *LockTransaction) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *LockTransaction) GetMintRecipient() string {
	if m != nil {
		return m.MintRecipient
	}
	return ""
}

func (m *LockTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LockTransaction) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *LockTransaction) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_ASSET_UNSPECIFIED
}

// PendingMintTransaction is the metadata for a pending zenBTC mint transaction.
type PendingMintTransaction struct {
	ChainId            uint64                `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // Deprecated: Do not use.
	ChainType          WalletType            `protobuf:"varint,2,opt,name=chain_type,json=chainType,proto3,enum=zrchain.dct.WalletType" json:"chain_type,omitempty"`
	RecipientAddress   string                `protobuf:"bytes,3,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	Amount             uint64                `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Creator            string                `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	KeyId              uint64                `protobuf:"varint,6,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // Deprecated: Do not use.
	Caip2ChainId       string                `protobuf:"bytes,7,opt,name=caip2_chain_id,json=caip2ChainId,proto3" json:"caip2_chain_id,omitempty"`
	Id                 uint64                `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	Status             MintTransactionStatus `protobuf:"varint,9,opt,name=status,proto3,enum=zrchain.dct.MintTransactionStatus" json:"status,omitempty"`
	ZrchainTxId        uint64                `protobuf:"varint,10,opt,name=zrchain_tx_id,json=zrchainTxId,proto3" json:"zrchain_tx_id,omitempty"`
	BlockHeight        int64                 `protobuf:"varint,11,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	AwaitingEventSince int64                 `protobuf:"varint,12,opt,name=awaiting_event_since,json=awaitingEventSince,proto3" json:"awaiting_event_since,omitempty"`
	TxHash             string                `protobuf:"bytes,13,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Asset              Asset                 `protobuf:"varint,14,opt,name=asset,proto3,enum=zrchain.dct.Asset" json:"asset,omitempty"`
}

func (m *PendingMintTransaction) Reset()         { *m = PendingMintTransaction{} }
func (m *PendingMintTransaction) String() string { return proto.CompactTextString(m) }
func (*PendingMintTransaction) ProtoMessage()    {}
func (*PendingMintTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{3}
}
func (m *PendingMintTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingMintTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingMintTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingMintTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingMintTransaction.Merge(m, src)
}
func (m *PendingMintTransaction) XXX_Size() int {
	return m.Size()
}
func (m *PendingMintTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingMintTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_PendingMintTransaction proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *PendingMintTransaction) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *PendingMintTransaction) GetChainType() WalletType {
	if m != nil {
		return m.ChainType
	}
	return WalletType_WALLET_TYPE_UNSPECIFIED
}

func (m *PendingMintTransaction) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *PendingMintTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PendingMintTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// Deprecated: Do not use.
func (m *PendingMintTransaction) GetKeyId() uint64 {
	if m != nil {
		return m.KeyId
	}
	return 0
}

func (m *PendingMintTransaction) GetCaip2ChainId() string {
	if m != nil {
		return m.Caip2ChainId
	}
	return ""
}

func (m *PendingMintTransaction) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PendingMintTransaction) GetStatus() MintTransactionStatus {
	if m != nil {
		return m.Status
	}
	return MintTransactionStatus_MINT_TRANSACTION_STATUS_UNSPECIFIED
}

func (m *PendingMintTransaction) GetZrchainTxId() uint64 {
	if m != nil {
		return m.ZrchainTxId
	}
	return 0
}

func (m *PendingMintTransaction) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PendingMintTransaction) GetAwaitingEventSince() int64 {
	if m != nil {
		return m.AwaitingEventSince
	}
	return 0
}

func (m *PendingMintTransaction) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *PendingMintTransaction) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_ASSET_UNSPECIFIED
}

// Deprecated: This message is deprecated and should no longer be used.
//
// Deprecated: Do not use.
type PendingMintTransactions struct {
	Txs []*PendingMintTransaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (m *PendingMintTransactions) Reset()         { *m = PendingMintTransactions{} }
func (m *PendingMintTransactions) String() string { return proto.CompactTextString(m) }
func (*PendingMintTransactions) ProtoMessage()    {}
func (*PendingMintTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6645623106a90320, []int{4}
}
func (m *PendingMintTransactions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingMintTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingMintTransactions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingMintTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingMintTransactions.Merge(m, src)
}
func (m *PendingMintTransactions) XXX_Size() int {
	return m.Size()
}
func (m *PendingMintTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingMintTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_PendingMintTransactions proto.InternalMessageInfo

func (m *PendingMintTransactions) GetTxs() []*PendingMintTransaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterEnum("zrchain.dct.MintTransactionStatus", MintTransactionStatus_name, MintTransactionStatus_value)
	proto.RegisterEnum("zrchain.dct.WalletType", WalletType_name, WalletType_value)
	proto.RegisterType((*NonceData)(nil), "zrchain.dct.NonceData")
	proto.RegisterType((*RequestedBitcoinHeaders)(nil), "zrchain.dct.RequestedBitcoinHeaders")
	proto.RegisterType((*LockTransaction)(nil), "zrchain.dct.LockTransaction")
	proto.RegisterType((*PendingMintTransaction)(nil), "zrchain.dct.PendingMintTransaction")
	proto.RegisterType((*PendingMintTransactions)(nil), "zrchain.dct.PendingMintTransactions")
}

func init() { proto.RegisterFile("zrchain/dct/mint.proto", fileDescriptor_6645623106a90320) }

var fileDescriptor_6645623106a90320 = []byte{
	// 836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x72, 0xdb, 0x36,
	0x10, 0x36, 0xf5, 0x6b, 0xad, 0x6d, 0x85, 0x45, 0x13, 0x89, 0x4d, 0x27, 0x1a, 0x45, 0x69, 0xa6,
	0x9a, 0x74, 0x2a, 0x75, 0x9c, 0x36, 0x87, 0xdc, 0x68, 0x8b, 0xa9, 0x39, 0xb5, 0x69, 0x0f, 0x88,
	0x24, 0xd3, 0x5c, 0x38, 0x30, 0x89, 0xb1, 0x30, 0xb2, 0x41, 0x95, 0x80, 0x6c, 0xb9, 0x4f, 0xd1,
	0x5b, 0x1f, 0xa3, 0x2f, 0xd1, 0x43, 0x8f, 0x39, 0xf6, 0x98, 0xb1, 0x5f, 0xa4, 0x03, 0x50, 0x72,
	0x64, 0x45, 0x6e, 0x6e, 0xd8, 0xef, 0xfb, 0x16, 0xf8, 0x76, 0xb1, 0x00, 0x34, 0x7e, 0xcf, 0xe2,
	0x21, 0xe5, 0xa2, 0x9f, 0xc4, 0xaa, 0x7f, 0xc6, 0x85, 0xea, 0x8d, 0xb3, 0x54, 0xa5, 0x68, 0x63,
	0x86, 0xf7, 0x92, 0x58, 0x3d, 0x74, 0x16, 0x45, 0x63, 0x9a, 0xd1, 0x33, 0x99, 0xcb, 0x3a, 0x02,
	0x6a, 0x41, 0x2a, 0x62, 0x36, 0xa0, 0x8a, 0xa2, 0xfb, 0x50, 0x16, 0x3a, 0x70, 0xac, 0xb6, 0xd5,
	0x2d, 0xe1, 0x3c, 0x40, 0x0e, 0x54, 0xe3, 0x74, 0x22, 0x14, 0xcb, 0x9c, 0x82, 0xc1, 0xe7, 0x21,
	0x42, 0x50, 0x92, 0x23, 0x3e, 0x76, 0x8a, 0x6d, 0xab, 0xbb, 0x8e, 0xcd, 0x1a, 0x3d, 0x02, 0x18,
	0x67, 0xec, 0x3c, 0xca, 0x37, 0x2a, 0x99, 0x84, 0x9a, 0x46, 0xcc, 0x31, 0x9d, 0xe7, 0xd0, 0xc4,
	0xec, 0xb7, 0x09, 0x93, 0x8a, 0x25, 0x3b, 0x5c, 0xc5, 0x29, 0x17, 0x7b, 0x8c, 0x26, 0x2c, 0x93,
	0xfa, 0x9c, 0x21, 0xe3, 0x27, 0x43, 0x25, 0x1d, 0xab, 0x5d, 0xec, 0x16, 0xf1, 0x3c, 0xec, 0x7c,
	0xb0, 0xe0, 0xde, 0x7e, 0x1a, 0x8f, 0x48, 0x46, 0x85, 0xa4, 0xb1, 0xe2, 0xa9, 0x40, 0x0f, 0xa0,
	0x92, 0xd1, 0x8b, 0x48, 0x4d, 0x8d, 0xd9, 0x1a, 0x2e, 0x67, 0xf4, 0x82, 0x4c, 0xb5, 0xa5, 0xf3,
	0x74, 0xa2, 0x66, 0x4e, 0xcd, 0x1a, 0x35, 0xa0, 0x22, 0x99, 0x48, 0x58, 0x66, 0x8c, 0xd6, 0xf0,
	0x2c, 0x42, 0x4f, 0xa1, 0xae, 0x1b, 0x16, 0x65, 0x2c, 0xe6, 0x63, 0xce, 0x84, 0x32, 0x76, 0x6b,
	0x78, 0x4b, 0xa3, 0x78, 0x0e, 0xea, 0x74, 0x7a, 0xa6, 0x2b, 0x76, 0xca, 0x66, 0xd3, 0x59, 0x84,
	0x1e, 0xc3, 0xe6, 0xf1, 0x69, 0x1a, 0x8f, 0xa2, 0xdc, 0xa6, 0x53, 0x69, 0x5b, 0xdd, 0x22, 0xde,
	0x30, 0xd8, 0x9e, 0x81, 0x50, 0x17, 0xca, 0x54, 0x4a, 0xa6, 0x9c, 0x6a, 0xdb, 0xea, 0xd6, 0xb7,
	0x51, 0x6f, 0xe1, 0x52, 0x7a, 0xae, 0x66, 0x70, 0x2e, 0xe8, 0xfc, 0x59, 0x82, 0xc6, 0x11, 0x13,
	0x09, 0x17, 0x27, 0x07, 0x5c, 0xa8, 0xc5, 0x4a, 0x1f, 0xc1, 0xba, 0x49, 0x8a, 0x78, 0x92, 0x5f,
	0xcc, 0x4e, 0xc1, 0xb1, 0x70, 0xd5, 0x60, 0x7e, 0x82, 0x5e, 0x00, 0xe4, 0xb4, 0xba, 0x1c, 0x33,
	0x53, 0x77, 0x7d, 0xbb, 0x79, 0xeb, 0xa0, 0xb7, 0xf4, 0xf4, 0x94, 0x29, 0x72, 0x39, 0x66, 0xb8,
	0x66, 0x50, 0xbd, 0x44, 0xdf, 0xc1, 0x17, 0x37, 0x85, 0x47, 0x34, 0x49, 0x32, 0x26, 0xe5, 0xac,
	0x41, 0xf6, 0x0d, 0xe1, 0xe6, 0xf8, 0x42, 0x0f, 0x4a, 0xb7, 0x7a, 0xa0, 0x67, 0x23, 0x63, 0x54,
	0xa5, 0x99, 0x69, 0x4e, 0x0d, 0xcf, 0x43, 0xf4, 0x15, 0x54, 0x46, 0xec, 0x52, 0x7b, 0xae, 0xdc,
	0x78, 0x2e, 0x8f, 0xd8, 0xa5, 0x9f, 0xa0, 0x6f, 0xa0, 0x1e, 0x53, 0x3e, 0xde, 0x8e, 0x6e, 0xca,
	0xaa, 0x9a, 0xdc, 0x4d, 0x83, 0xee, 0xce, 0xea, 0xaa, 0x43, 0x81, 0x27, 0xce, 0xba, 0x39, 0xae,
	0xc0, 0x13, 0xf4, 0x12, 0x2a, 0x52, 0x51, 0x35, 0x91, 0x4e, 0xcd, 0xd4, 0xd8, 0xb9, 0x55, 0xe3,
	0x52, 0xd3, 0x42, 0xa3, 0xc4, 0xb3, 0x0c, 0xd4, 0x81, 0xad, 0x99, 0x38, 0x52, 0x53, 0x7d, 0x20,
	0x98, 0x6d, 0xe7, 0x6f, 0x84, 0x4c, 0xfd, 0xe4, 0x93, 0xeb, 0xdc, 0xf8, 0xf4, 0x3a, 0x7f, 0x80,
	0xfb, 0xf4, 0x82, 0x72, 0xc5, 0xc5, 0x49, 0xc4, 0xce, 0x75, 0xdf, 0x24, 0xd7, 0x53, 0xbe, 0x69,
	0xa4, 0x68, 0xce, 0x79, 0x9a, 0x0a, 0x35, 0x83, 0x9a, 0x50, 0x55, 0xd3, 0x68, 0x48, 0xe5, 0xd0,
	0xd9, 0xca, 0x67, 0x4f, 0x4d, 0xf7, 0xa8, 0x1c, 0x7e, 0x9c, 0x8c, 0xfa, 0xe7, 0x26, 0x83, 0x40,
	0x73, 0xf5, 0x60, 0x48, 0xf4, 0x13, 0x14, 0xd5, 0x34, 0x7f, 0x2d, 0x1b, 0xdb, 0x4f, 0x6e, 0x6d,
	0xb1, 0x3a, 0x05, 0x6b, 0xfd, 0xcb, 0x82, 0x63, 0x3d, 0xfb, 0xcb, 0x82, 0x07, 0x2b, 0x7b, 0x86,
	0xbe, 0x85, 0x27, 0x07, 0x7e, 0x40, 0x22, 0x82, 0xdd, 0x20, 0x74, 0x77, 0x89, 0x7f, 0x18, 0x44,
	0x21, 0x71, 0xc9, 0xeb, 0x30, 0x7a, 0x1d, 0x84, 0x47, 0xde, 0xae, 0xff, 0xca, 0xf7, 0x06, 0xf6,
	0x1a, 0x7a, 0x0a, 0x8f, 0xef, 0x12, 0x0e, 0xbc, 0xa3, 0xc3, 0xd0, 0x27, 0xde, 0xc0, 0xb6, 0x50,
	0x07, 0x5a, 0x77, 0xc9, 0x42, 0xe2, 0xfe, 0xe2, 0x0d, 0xec, 0xc2, 0xff, 0x69, 0x34, 0xee, 0x0d,
	0xec, 0xe2, 0xb3, 0xbf, 0x2d, 0x80, 0x8f, 0x93, 0x8c, 0xbe, 0x86, 0xe6, 0x5b, 0x77, 0x7f, 0xdf,
	0x23, 0x11, 0xf9, 0xf5, 0xc8, 0x5b, 0xb2, 0xd6, 0x00, 0xb4, 0x48, 0x06, 0x2e, 0xf1, 0xdf, 0x78,
	0xb6, 0x85, 0xbe, 0x84, 0x7b, 0x8b, 0xb8, 0xf7, 0xe6, 0xc0, 0x2e, 0x2c, 0xef, 0xb4, 0x43, 0x76,
	0x23, 0xe2, 0x85, 0x24, 0xf0, 0x88, 0x5d, 0x5c, 0x45, 0x1e, 0xb8, 0x7e, 0xa0, 0xc9, 0x12, 0x7a,
	0x08, 0x8d, 0x65, 0x12, 0x7b, 0x3f, 0x6b, 0xae, 0xbc, 0x6c, 0x21, 0x3c, 0xdc, 0x77, 0x03, 0xd7,
	0xae, 0xec, 0x04, 0xff, 0x5c, 0xb5, 0xac, 0xf7, 0x57, 0x2d, 0xeb, 0xc3, 0x55, 0xcb, 0xfa, 0xe3,
	0xba, 0xb5, 0xf6, 0xfe, 0xba, 0xb5, 0xf6, 0xef, 0x75, 0x6b, 0xed, 0xdd, 0x8f, 0x27, 0x5c, 0x0d,
	0x27, 0xc7, 0xbd, 0x38, 0x3d, 0xeb, 0xbf, 0x63, 0x22, 0x4b, 0xe3, 0xd1, 0xf7, 0xaf, 0xd2, 0x89,
	0x48, 0xa8, 0xbe, 0x9d, 0xfe, 0xfc, 0x0b, 0x3f, 0x7f, 0xd1, 0x9f, 0x9a, 0x7f, 0x5c, 0xbf, 0x77,
	0x79, 0x5c, 0x31, 0xff, 0xf8, 0xf3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xcc, 0x52, 0xd9,
	0x08, 0x06, 0x00, 0x00,
}

func (m *NonceData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NonceData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NonceData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PrevNonce != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.PrevNonce))
		i--
		dAtA[i] = 0x20
	}
	if m.Skip {
		i--
		if m.Skip {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Counter != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Counter))
		i--
		dAtA[i] = 0x10
	}
	if m.Nonce != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RequestedBitcoinHeaders) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestedBitcoinHeaders) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestedBitcoinHeaders) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Heights) > 0 {
		dAtA2 := make([]byte, len(m.Heights)*10)
		var j1 int
		for _, num1 := range m.Heights {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintMint(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LockTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Asset != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x38
	}
	if m.BlockHeight != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.Amount != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MintRecipient) > 0 {
		i -= len(m.MintRecipient)
		copy(dAtA[i:], m.MintRecipient)
		i = encodeVarintMint(dAtA, i, uint64(len(m.MintRecipient)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMint(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Vout != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Vout))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RawTx) > 0 {
		i -= len(m.RawTx)
		copy(dAtA[i:], m.RawTx)
		i = encodeVarintMint(dAtA, i, uint64(len(m.RawTx)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingMintTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingMintTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingMintTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Asset != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x70
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintMint(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x6a
	}
	if m.AwaitingEventSince != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.AwaitingEventSince))
		i--
		dAtA[i] = 0x60
	}
	if m.BlockHeight != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.ZrchainTxId != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.ZrchainTxId))
		i--
		dAtA[i] = 0x50
	}
	if m.Status != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	if m.Id != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Caip2ChainId) > 0 {
		i -= len(m.Caip2ChainId)
		copy(dAtA[i:], m.Caip2ChainId)
		i = encodeVarintMint(dAtA, i, uint64(len(m.Caip2ChainId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.KeyId != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.KeyId))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMint(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Amount != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RecipientAddress) > 0 {
		i -= len(m.RecipientAddress)
		copy(dAtA[i:], m.RecipientAddress)
		i = encodeVarintMint(dAtA, i, uint64(len(m.RecipientAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ChainType != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.ChainType))
		i--
		dAtA[i] = 0x10
	}
	if m.ChainId != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PendingMintTransactions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingMintTransactions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingMintTransactions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Txs) > 0 {
		for iNdEx := len(m.Txs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Txs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMint(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintMint(dAtA []byte, offset int, v uint64) int {
	offset -= sovMint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NonceData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovMint(uint64(m.Nonce))
	}
	if m.Counter != 0 {
		n += 1 + sovMint(uint64(m.Counter))
	}
	if m.Skip {
		n += 2
	}
	if m.PrevNonce != 0 {
		n += 1 + sovMint(uint64(m.PrevNonce))
	}
	return n
}

func (m *RequestedBitcoinHeaders) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Heights) > 0 {
		l = 0
		for _, e := range m.Heights {
			l += sovMint(uint64(e))
		}
		n += 1 + sovMint(uint64(l)) + l
	}
	return n
}

func (m *LockTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RawTx)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.Vout != 0 {
		n += 1 + sovMint(uint64(m.Vout))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	l = len(m.MintRecipient)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovMint(uint64(m.Amount))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovMint(uint64(m.BlockHeight))
	}
	if m.Asset != 0 {
		n += 1 + sovMint(uint64(m.Asset))
	}
	return n
}

func (m *PendingMintTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovMint(uint64(m.ChainId))
	}
	if m.ChainType != 0 {
		n += 1 + sovMint(uint64(m.ChainType))
	}
	l = len(m.RecipientAddress)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovMint(uint64(m.Amount))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.KeyId != 0 {
		n += 1 + sovMint(uint64(m.KeyId))
	}
	l = len(m.Caip2ChainId)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovMint(uint64(m.Id))
	}
	if m.Status != 0 {
		n += 1 + sovMint(uint64(m.Status))
	}
	if m.ZrchainTxId != 0 {
		n += 1 + sovMint(uint64(m.ZrchainTxId))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovMint(uint64(m.BlockHeight))
	}
	if m.AwaitingEventSince != 0 {
		n += 1 + sovMint(uint64(m.AwaitingEventSince))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.Asset != 0 {
		n += 1 + sovMint(uint64(m.Asset))
	}
	return n
}

func (m *PendingMintTransactions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Txs) > 0 {
		for _, e := range m.Txs {
			l = e.Size()
			n += 1 + l + sovMint(uint64(l))
		}
	}
	return n
}

func sovMint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMint(x uint64) (n int) {
	return sovMint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NonceData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NonceData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NonceData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			m.Counter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Counter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skip", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Skip = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevNonce", wireType)
			}
			m.PrevNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrevNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestedBitcoinHeaders) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestedBitcoinHeaders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestedBitcoinHeaders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMint
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Heights = append(m.Heights, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMint
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMint
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthMint
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Heights) == 0 {
					m.Heights = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMint
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Heights = append(m.Heights, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Heights", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LockTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LockTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LockTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawTx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawTx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vout", wireType)
			}
			m.Vout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= Asset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingMintTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingMintTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingMintTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainType", wireType)
			}
			m.ChainType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainType |= WalletType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyId", wireType)
			}
			m.KeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Caip2ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Caip2ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= MintTransactionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZrchainTxId", wireType)
			}
			m.ZrchainTxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ZrchainTxId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AwaitingEventSince", wireType)
			}
			m.AwaitingEventSince = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AwaitingEventSince |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= Asset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingMintTransactions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingMintTransactions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingMintTransactions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txs = append(m.Txs, &PendingMintTransaction{})
			if err := m.Txs[len(m.Txs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMint = fmt.Errorf("proto: unexpected end of group")
)
