// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zrchain/dct/supply.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Supply struct {
	Asset           Asset  `protobuf:"varint,1,opt,name=asset,proto3,enum=zrchain.dct.Asset" json:"asset,omitempty"`
	CustodiedAmount uint64 `protobuf:"varint,2,opt,name=custodied_amount,json=custodiedAmount,proto3" json:"custodied_amount,omitempty"`
	MintedAmount    uint64 `protobuf:"varint,3,opt,name=minted_amount,json=mintedAmount,proto3" json:"minted_amount,omitempty"`
	PendingAmount   uint64 `protobuf:"varint,4,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
}

func (m *Supply) Reset()         { *m = Supply{} }
func (m *Supply) String() string { return proto.CompactTextString(m) }
func (*Supply) ProtoMessage()    {}
func (*Supply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df27074f887fa10, []int{0}
}
func (m *Supply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Supply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Supply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Supply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supply.Merge(m, src)
}
func (m *Supply) XXX_Size() int {
	return m.Size()
}
func (m *Supply) XXX_DiscardUnknown() {
	xxx_messageInfo_Supply.DiscardUnknown(m)
}

var xxx_messageInfo_Supply proto.InternalMessageInfo

func (m *Supply) GetAsset() Asset {
	if m != nil {
		return m.Asset
	}
	return Asset_ASSET_UNSPECIFIED
}

func (m *Supply) GetCustodiedAmount() uint64 {
	if m != nil {
		return m.CustodiedAmount
	}
	return 0
}

func (m *Supply) GetMintedAmount() uint64 {
	if m != nil {
		return m.MintedAmount
	}
	return 0
}

func (m *Supply) GetPendingAmount() uint64 {
	if m != nil {
		return m.PendingAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*Supply)(nil), "zrchain.dct.Supply")
}

func init() { proto.RegisterFile("zrchain/dct/supply.proto", fileDescriptor_5df27074f887fa10) }

var fileDescriptor_5df27074f887fa10 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xa8, 0x2a, 0x4a, 0xce,
	0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0x49, 0x2e, 0xd1, 0x2f, 0x2e, 0x2d, 0x28, 0xc8, 0xa9, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0xca, 0xe8, 0xa5, 0x24, 0x97, 0x48, 0xa1, 0x28, 0x2b,
	0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0x86, 0x28, 0x53, 0x5a, 0xc9, 0xc8, 0xc5, 0x16, 0x0c, 0xd6, 0x27,
	0xa4, 0xc1, 0xc5, 0x9a, 0x58, 0x5c, 0x9c, 0x5a, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x24,
	0xa4, 0x87, 0x64, 0x82, 0x9e, 0x23, 0x48, 0x26, 0x08, 0xa2, 0x40, 0x48, 0x93, 0x4b, 0x20, 0xb9,
	0xb4, 0xb8, 0x24, 0x3f, 0x25, 0x33, 0x35, 0x25, 0x3e, 0x31, 0x37, 0xbf, 0x34, 0xaf, 0x44, 0x82,
	0x49, 0x81, 0x51, 0x83, 0x25, 0x88, 0x1f, 0x2e, 0xee, 0x08, 0x16, 0x16, 0x52, 0xe6, 0xe2, 0xcd,
	0xcd, 0xcc, 0x2b, 0x41, 0xa8, 0x63, 0x06, 0xab, 0xe3, 0x81, 0x08, 0x42, 0x15, 0xa9, 0x72, 0xf1,
	0x15, 0xa4, 0xe6, 0xa5, 0x64, 0xe6, 0xa5, 0xc3, 0x54, 0xb1, 0x80, 0x55, 0xf1, 0x42, 0x45, 0x21,
	0xca, 0x9c, 0xfc, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6,
	0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x24, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x2a, 0x35, 0xaf, 0x28, 0x3f, 0x39,
	0x5b, 0xd7, 0x2d, 0xbf, 0x34, 0x2f, 0x25, 0xb1, 0x24, 0x33, 0x3f, 0x4f, 0x1f, 0xe6, 0xfb, 0x32,
	0x33, 0xfd, 0x0a, 0x70, 0x10, 0x94, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x83, 0xc0, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xf1, 0x37, 0xba, 0x45, 0x01, 0x00, 0x00,
}

func (m *Supply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Supply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Supply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PendingAmount != 0 {
		i = encodeVarintSupply(dAtA, i, uint64(m.PendingAmount))
		i--
		dAtA[i] = 0x20
	}
	if m.MintedAmount != 0 {
		i = encodeVarintSupply(dAtA, i, uint64(m.MintedAmount))
		i--
		dAtA[i] = 0x18
	}
	if m.CustodiedAmount != 0 {
		i = encodeVarintSupply(dAtA, i, uint64(m.CustodiedAmount))
		i--
		dAtA[i] = 0x10
	}
	if m.Asset != 0 {
		i = encodeVarintSupply(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSupply(dAtA []byte, offset int, v uint64) int {
	offset -= sovSupply(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Supply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Asset != 0 {
		n += 1 + sovSupply(uint64(m.Asset))
	}
	if m.CustodiedAmount != 0 {
		n += 1 + sovSupply(uint64(m.CustodiedAmount))
	}
	if m.MintedAmount != 0 {
		n += 1 + sovSupply(uint64(m.MintedAmount))
	}
	if m.PendingAmount != 0 {
		n += 1 + sovSupply(uint64(m.PendingAmount))
	}
	return n
}

func sovSupply(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSupply(x uint64) (n int) {
	return sovSupply(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Supply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSupply
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Supply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Supply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= Asset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodiedAmount", wireType)
			}
			m.CustodiedAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CustodiedAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedAmount", wireType)
			}
			m.MintedAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintedAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAmount", wireType)
			}
			m.PendingAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSupply(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSupply
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSupply(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSupply
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSupply
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSupply
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSupply
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSupply
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSupply
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSupply        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSupply          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSupply = fmt.Errorf("proto: unexpected end of group")
)
